#!/usr/bin/python
from base64 import b64decode
from contextlib import contextmanager
from threading import Thread, Event
from datetime import datetime
from loguru import logger
import subprocess as sp
import uuid
import time
import sys
import os

class Source:
    def __init__(self):
        self.start = datetime.now()
        self.terminate = Event()
        self.note_id = uuid.uuid4().hex
        logger.remove()
        logfmt = '<green>{time:%H:%M:%S}</green>|<level>{level}</level>|<level>{message}</level>'
        logger.add(sys.stderr, colorize=True, format=logfmt, level='INFO')
        logger.info('[grammer] started')
        logger.info(self.note_id)

    def notification(self, fifo_path, title=None, content=None):
        if not title:
            title ='Test'
        if not content:
            content ='placeholder'
        # --
        task = sp.run([
            'termux-notification-remove',
            self.note_id
        ])
        # --
        task = sp.run([
            'termux-notification',
            '-i', self.note_id,
            '-t', title,
            '-c', content,
            '--button1', 'reply',
            f'--button1-action', f'echo $REPLY>{fifo_path}'
        ])

    def toast(self, content=None):
        if not content:
            content ='placeholder'
        # --
        task = sp.run([
            'termux-toast',
            '-b', 'black',
            '-g', 'top',
            content,
        ])

    def pip(self, command):
        logger.debug(command)
        task = sp.run([
            '/data/data/com.termux/files/usr/bin/pip',
            *command.split(' ')[1:]
        ])

    def server(self):
        fifo = 'transport'
        if os.path.exists(fifo):
            os.unlink(fifo)
        # --
        os.mkfifo(fifo)
        cwd = os.getcwd()
        fifo_path = os.path.join(cwd, fifo)
        # --
        def read_fifo(fpath):
            self.notification(fpath)
            while not self.terminate.is_set():
                try:
                    with open(fifo, 'r') as fd:
                        response = fd.read().strip('\n')
                        self.toast('Processing response...')
                    yield response
                except KeyboardInterrupt:
                    logger.info('keyboard interrupt')
                    self.terminate.set()
                    break
            # print('deleting fpath')
            os.unlink(fpath)
        # --
        for response in read_fifo(fifo_path):
            if response[:3] == 'pip':
                self.pip(command=response)
            else:
                try:
                    compiled = compile(response, filename='runtime.bin', mode='exec', dont_inherit=True)
                    exec(compiled)
                except Exception as e:
                    logger.exception(e)
                    self.notification(fifo_path, title='exception', content=str(e))
                logger.info(response)
 
    def local(self):
        self.server()
        task = sp.run([
            'termux-notification-remove',
            self.note_id
        ])
#********************* <start>
def initialize():
    bot = Source()
    bot.local()
#-- </start>

initialize()

