#!/usr/bin/bash
# --
apt update
apt install clang python gnupg tree which neovim termux-api file
python -m venv .venv

# --
source ~/.venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
