#!/usr/bin/python
from contextlib import contextmanager
from threading import Thread, Event
from datetime import datetime
from base64 import b64decode
from loguru import logger
import subprocess as sp
import uuid
import time
import sys
import os

class Source:
    runtime = {
        'code': dict(),
        'commands': dict(),
        'actions': dict()
    }
    def __init__(self):
        self.start = datetime.now()
        self.terminate = Event()
        self.instance_id = uuid.uuid4().hex
        logger.remove()
        logfmt = '<green>{line}</green>|<level>{level}</level>|<level>{message}</level>'
        logger.add(sys.stderr, colorize=True, format=logfmt, level='DEBUG')
        logger.info('[{}] started', self.instance_id)

    def notification(self, fifo_path, title=None, content=None):
        if not title:
            title ='river'
        if not content:
            content ='Enter command or code snippet.'
        # --
        task = sp.run([
            'termux-notification-remove',
            self.instance_id
        ])
        # --
        task = sp.run([
            'termux-notification',
            '-i', self.instance_id,
            '-t', title,
            '-c', content,
            '--button1', 'reply',
            f'--button1-action', f'echo $REPLY>{fifo_path}'
        ])

    def toast(self, content=None):
        if not content:
            content ='placeholder'
        # --
        task = sp.run([
            'termux-toast',
            '-b', 'black',
            '-g', 'top',
            content,
        ])

    @staticmethod
    def module(module_fn, module_name, module_type):
        def wrapper(module_fn):
            logger.debug('module_name: {}', module_name)
            logger.debug('module_type: {}', module_type)
            Source.runtime[module_type][module_name] = module_fn
            return module_fn
        return wrapper(module_fn)

    @staticmethod
    def module_call(module_name, module_type, *args, **kwargs):
        if module_type in Source.runtime:
            if (module:=Source.runtime[module_type].get(module_name)):
                try:
                    logger.debug('{} call:  {}', module_type, module_name)
                    return module(*args, **kwargs)
                except Exception as e:
                    logger.exception(e)

    def initialize(self):
        def pip(command):
            task = sp.Popen([
                '/data/data/com.termux/files/usr/bin/pip',
                *command.split(' ')[1:]
            ], shell=False, stdout=sp.PIPE)
            task.wait()
            return task.returncode, task.stdout.read().decode()
        # --
        pip = Source.module(pip, 'pip','commands')
        # --
        logger.debug('code: {}', len(self.runtime['code']))
        logger.debug('commands: {}', len(self.runtime['commands']))
        logger.debug('actions: {}', len(self.runtime['code']))

    def server(self):
        fifo = 'transport'
        if os.path.exists(fifo):
            os.unlink(fifo)
        # --
        os.mkfifo(fifo)
        cwd = os.getcwd()
        fifo_path = os.path.join(cwd, fifo)
        # --
        def read_fifo(fpath):
            self.notification(fpath)
            while not self.terminate.is_set():
                try:
                    with open(fifo, 'r') as fd:
                        response = fd.read().strip('\n')
                        response_id = uuid.uuid4().hex
                        self.toast('Processing response...')
                    yield response, response_id
                    self.notification(fpath)
                except KeyboardInterrupt:
                    logger.info('keyboard interrupt')
                    self.terminate.set()
                    break
            # print('deleting fpath')
            os.unlink(fpath)
        # --
        def command_exists(command):
            command_name = command.split(' ')[0]
            if command_name in self.runtime['commands']:
                return command_name
        # --
        for response, response_id in read_fifo(fifo_path):
            if command:=command_exists(response):
                retcode, output = Source.module_call(command, 'commands', response)
                logger.debug('{}:<{}>:{}'.format(response_id, retcode, response))
                logger.debug('[output]\n{}', output)
            else:
                try:
                    logger.debug('response_id: {}', response_id)
                    compiled = compile(response, filename='<string>', mode='exec')
                    exec(compiled, globals={'main': self})
                except Exception as e:
                    logger.exception(e)
                    self.toast(str(e))
                logger.info(response)
 
    def local(self):
        self.initialize()
        self.server()
        task = sp.run([
            'termux-notification-remove',
            self.instance_id
        ])
#********************* <start>
def initialize():
    bot = Source()
    bot.local()
#-- </start>

initialize()

