#!/usr/bin/python
import os
import json
import getpass
import requests

URL = "https://duck.com/search?q={}"

# Your API key from environment variable
# api_key = os.getenv("GROQ_API_KEY")
# --
def main():
    clear = lambda: os.system('clear')
    while 1:
        query = str(input('Query: '))
        if not query:
            continue
        # --
        clear()
        # --
        try:
            response = requests.post(URL.format(query))
            response.raise_for_status()
            print(response)
        except requests.exceptions.RequestException as e:
            print(f"Request failed: {e}")

if __name__ == '__main__':
    main()

