#!/usr/bin/python
#source: grammer
#license: GPLv2
from base64 import b64encode, b64decode
from contextlib import contextmanager
from threading import Thread, Event
from time import perf_counter
from datetime import datetime
from loguru import logger
from socket import socket
import subprocess as sp
import hashlib
import sys
import os
from socket import(
    AF_INET,
    SOL_SOCKET,
    SOCK_STREAM,
    SO_REUSEADDR
)


# --
class Source:
    runtime = {
        'code': dict(),
        'commands': dict(),
        'threads': dict()
    }
    def __init__(self):
        self.out_buffer = list()
        self.terminate = Event()
        self.start = datetime.now()
        self.text ='Enter command or code snippet.'
        self.socket = self.initialize()
        self.instance_name, self.instance_id = self.load()
        self.fifo = os.path.join(os.getcwd(), self.instance_id)
        logger.info('[{}] started', self.instance_name)

    def add_code(self, name:str, base64_code: str, requirements= str()):
        """Add code to self.code. Only root file has noedit"""
        editable = True
        if os.path.exists(name):
            editable = False
        # --
        metahead = '#?'
        code = b64decode(base64_code).decode()
        if not len(requirements):
            metahead_lines = [i.replace(metahead, '') for i in code.split('\n') if metahead in i]
            meta = list()
            for line in metahead_lines:
                for required in [i for i in line.split(',') if i]:
                    if '=' not in required:
                        meta.append(f'{required}>=0.0.1')
            requirements = ','.join(meta).strip(',')
        # --
        requires = requirements.strip(',').split(',')
        def get_module(modname):
            for module in self.runtime['code'].values():
                for mod in module['requirements']:
                    logger.warning(mod)
            return False, False
        # --
        for dependancy in requires:
            lock = True
            installed = get_module(dependancy)
            logger.debug('installed: {}, requested: {}', installed, dependancy)
            depname, depver = None, None
            if '>' in dependancy:
                lock = False
                depname, depver = dependancy.split('>')
                depver = depver.strip('=')
            else:
                depname, depver = dependancy.split('==')
            # --
        # --
        code_hash = hashlib.sha512(base64_code)
        hash_algorithm = code_hash.name
        source_digest = code_hash.hexdigest()
        if stored := self.runtime['code'].get(name):
            if not stored['editable']:
                if stored['digest'] != source_digest:
                    logger.warning('Attempt to modify {}', name)
                    return None, None, None
                return name, hash_algorithm, source_digest
        # Parse modification time
        mod_time = datetime.now()
        if not editable:
            check_modification = f'terminal date -r {name}'
            time_str = self.module_call('terminal', 'commands', check_modification)
            time_str = time_str[1].strip('\n')
            mod_time = datetime.strptime(time_str, "%a %b %d %H:%M:%S EAT %Y")
        # todo: check code for sensitive functionality
        self.runtime['code'][name] = {
            'idle': True,
            'modified': mod_time,
            'editable': editable,
            'source': base64_code,
            'digest': source_digest,
            'requirements': requires
        }
        # logger.debug(self.runtime['code'][name])
        return name, hash_algorithm, source_digest

    def load(self):
        requirements = os.path.join(os.getcwd(), 'requirements.txt')
        if not os.path.exists(requirements):
            raise RuntimeError('missing dependencies')
        # --
        with open(requirements, 'r') as rf:
            requires = [i.strip('\n').strip() for i in rf.readlines()]
        # --
        source_name = sys.argv[0]
        source = b64encode(sys.stdin.read().encode())
        requires = ','.join(requires)
        self.add_code(source_name, source, requires)
        # name, _, digest = self.add_code(source_name, source, ','.join(requires))
        # self.runtime['code'][name]['idle'] = self.stopped
        # # --
        beacon = 'grammer-beacon'
        with open(beacon, 'rb') as b:
            beacon_src = b64encode(b.read())
            self.add_code(beacon, beacon_src)
            # _, _, b_digest = self.add_code(beacon, beacon_src)
            # logger.debug('beacon digest: {}', b_digest[-8:])
        # return name, digest
        logger.warning('debug exit')
        exit(0)
        return 'test', 'test'

    @contextmanager
    @staticmethod
    def timeit(name='timed process'):
        init = perf_counter()
        yield
        fin = perf_counter()
        logger.debug(f'{name} took: {fin - init:.2f}')

    def notificationr(self):
        with Source.timeit('notification-remove'):
            task = sp.run([
                'termux-notification-remove',
                self.instance_id
            ])

    def notification(self, title=None, content=None):
        if not title:
            start = len(self.instance_id) - 16
            title = '{}({})'.format(self.instance_name, self.instance_id[start:])
        if not content:
            content = self.text
        # --
        with Source.timeit('notification'):
            task = sp.run([
                'termux-notification',
                '--alert-once',
                '--ongoing',
                '-i', self.instance_id,
                '-t', title,
                '-c', content,
                '--button1', 'reply',
                f'--button1-action', f'echo $REPLY>{self.fifo}'
            ])

    def clipboard(self):
        with Source.timeit('clipboard-set'):
            task = sp.run([
                'termux-clipboard-set',
                '\n'.join([i.strip('\n').strip() for i in self.out_buffer]).encode()
            ])

    def toast(self, content=None):
        if not content:
            content = self.text
        # --
        content = str(content)
        with Source.timeit('toast'):
            task = sp.run([
                'termux-toast',
                '-b', 'white',
                '-c', 'black',
                '-g', 'top',
                content
            ])

    @staticmethod
    def module(module_fn, module_name, module_type):
        def wrapper(module_fn):
            logger.debug('module loaded: {}, {}'.format(module_name, module_type)) 
            Source.runtime[module_type][module_name] = {
                'callback': module_fn,
                'metadata': {}
            }
            return module_fn
        return wrapper(module_fn)

    @staticmethod
    def module_call(module_name, module_type, *args, **kwargs):
        if module_type in Source.runtime:
            if (module:=Source.runtime[module_type].get(module_name)):
                try:
                    logger.debug('{} call:  {}', module_type, module_name)
                    with Source.timeit(module_name):
                        return module['callback'](*args, **kwargs)
                except Exception as e:
                    logger.exception(e)

    def initialize(self):
        logger.remove()
        logfmt = '{time:HH:MM:ss}|<green>{line: <4}</green>|<level>{level}</level>|<level>{message}</level>'
        logger.add(sys.stdout, colorize=False, format=logfmt, level='DEBUG')
        logger.add(lambda x: self.out_buffer.append(x), colorize=False, format=logfmt, level='DEBUG')
        def terminal(command):
            task = sp.Popen(
                [*command.split(' ')[1:]],
                stdout=sp.PIPE,
                stderr=sp.PIPE,
                shell=False,
            )
            task.wait()
            return task.returncode, task.stdout.read().decode(), task.stderr.read().decode()
        # --
        def pip(command):
            task = sp.Popen([
                '/data/data/com.termux/files/usr/bin/pip',
                *command.split(' ')[1:]
            ], shell=False, stdout=sp.PIPE)
            task.wait()
            return task.returncode, task.stdout.read().decode()
        # --
        def shutdown(*args, **kwargs):
            self.text = 'shutting down...'
            self.toast()
            retcode = 0
            self.terminate.set()
            return retcode, self.text
        # --
        Source.module(pip, 'pip','commands')
        Source.module(terminal, 'terminal','commands')
        Source.module(shutdown, 'shutdown','commands')
        # --
        sock = socket(AF_INET, SOCK_STREAM)
        sock.bind(('0.0.0.0', 9097))
        sock.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
        sock.listen()
        return sock

    def server(self):
        # --
        def read_fifo():
            if os.path.exists(self.fifo):
                os.unlink(self.fifo)
            # --
            os.mkfifo(self.fifo)
            while not self.terminate.is_set():
                try:
                    with open(self.fifo, 'r') as fd:
                        response = fd.read().strip('\n')
                        response_id = uuid.uuid4().hex
                    yield response, response_id
                except KeyboardInterrupt:
                    logger.info('keyboard interrupt')
                    self.terminate.set()
                    break
            # --
            if os.path.exists(self.fifo):
                os.unlink(self.fifo)
        # --
        def command_exists(command):
            command_name = command.split(' ')[0]
            # --
            if command_name in self.runtime['commands']:
                return command_name
        # --
        self.notification()
        for response, response_id in read_fifo():
            if command:=command_exists(response):
                with Source.timeit(command):
                    output = Source.module_call(command, 'commands', response)
                    logger.debug(output)
                    if not isinstance(output, str):
                        output= str(output)
                    logger.debug('command: {}, output: \n{}', command, output)
                self.clipboard()
            else:
                try:
                    nametag = '#[]'
                    codename = response.split('\n')[0]
                    tags_found = 0
                    for ch in nametag:
                        if ch in codename:
                            tags_found += 1
                    if tags_found != 3:
                        codename = '<code>'
                    else:
                        codename = re.search('\\w', codename).string()
                    code = b64encode(response.encode())
                    name, algo, digest = self.add_code(codename, code)
                    logger.debug('added code: name({}), algo({}), digest({})', name, algo, digest)
                    # -- todo: delayed code run
                    # -- todo: run code in persistent session
                    # compiled = compile(response, filename=codename, mode='exec')
                    # globalz = {
                    #     'root': self,
                    #     'logger': logger,
                    #     'thread': Thread,
                    #     'print': logger.debug,
                    #     'stdout': self.out_buffer,
                    #     'stopped': self.stopped
                    # }
                    # exec(compiled, locals=globalz)
                    # self.clipboard()
                except Exception as e:
                    logger.exception(e)
                    self.clipboard()

    def thread(self, function, *args, **kwargs):
        def function_call(metadata):
            metadata['exited'].clear()
            metadata['callable'](*metadata['args'], **metadata['kwargs'])
            metadata['exited'].set()
        # --
        fn_name = function.__name__
        self.runtime['threads'][fn_name] = {
            'exited' : Event(),
            'callable' : function,
            'kwargs': kwargs,
            'args': args
        }
        metadata = self.runtime['threads'][fn_name]
        t = Thread(target=function_call, args=(metadata,))
        metadata['workthread'] = t
        t.start()

    @property
    def stop(self):
        return self.terminate.set()

    @property
    def stopped(self):
        return self.terminate.is_set()

    def local(self):
        self.server()
        self.notificationr()
        self.out_buffer.clear()
#********************* <start>
def initialize():
    bot = Source()
    bot.local()
#-- </start>

if __name__ == '__main__':
    initialize()

