#!/usr/bin/python
from base64 import b64encode
from socket import create_connection

conn = create_connection(('0.0.0.0', 9797))
print(dir(conn))

# -- download beacon script
initialized = False

while not initialized:
    print(conn.recv(1024))
    initialized = True
    conn.send('\n'.encode())

print('--end--')


