#!/usr/bin/bash
if ! [ -d ~/.venv ]; then
    apt update && apt upgrade;
    apt install zsh curl openssh git python gnupg tree which neovim termux-api file htop;
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)";
    python -m venv .venv;
fi

# --
if [ -d ~/.venv ]; then
    source ~/.venv/bin/activate;
    pip install --upgrade pip;
    pip install -r requirements.txt;
    apt purge clang -y;
    apt autoclean;
    apt autoremove;
fi

